name: Gradle Package

on:
  release:
    types: [published]

env:
  TAG_NAME: ${{ github.event.release.tag_name }}

jobs:
  publish:
#    if: ${{ github.event.release.target_commitish == 'master' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Wat the event
      run: echo "Commitish is ${{ github.event.release.target_commitish }} at $GITHUB_REF"

    - name: Build with Gradle
      run: "./gradlew build -Pversion=${TAG_NAME#v}"

    - name: Publish to GitHub Packages
      run: "./gradlew publish -Pversion=${TAG_NAME#v}"
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

