name: Gradle Package

on:
  release:
    types: [published]

jobs:
  publish:
    if: ${{ github.event.target_commitish == 'master' }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Gradle
      run: "./gradlew build -Pversion=${GITHUB_REF#v}"

    - name: Publish to GitHub Packages
      run: "./gradlew publish -Pversion=${GITHUB_REF#v}"
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

